### ISSUE TITLE
Synergies with similar libraries?

### ISSUE THREAD

**Issue by nissimsan** [jiaoxlong/json-to-rdf-shacl#5]
Great work on this repo! Bravo! 💯

I'm wondering if you guys have looked at other similar libraries for inspiration? For example https://github.com/transmute-industries/verifiable-data/tree/main/packages/jsonld-schema (which is used to drive https://github.com/w3c-ccg/traceability-vocab). Your use of RDFS and SHAQL is particularly interesting. Both in TS, and with roughly the same goal - I'd love to join forces. 

Open ended question: do you see any opportunities for repo-synergies?

**Comment by jiaoxlong** [comment]
Thank you for expressing your interest in jsc-ld. After reviewing the jsonld-schema library, I do not think we have the same goal (rdf vs json-ld). Thus, let us keep in touch for future opportunities.
